apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: jpnino/cloud-config:latest
        ports:
        - containerPort: 9296
        env:
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://zipkin:9411
        - name: EUREKA_CLIENT_REGION
          value: default
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: myzone
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: http://service-discovery:8761/eureka
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://service-discovery:8761/eureka/
        - name: EUREKA_INSTANCE
          value: "cloud-config"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: cloud-config
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config
spec:
  selector:
    app: cloud-config
  ports:
  - port: 9296
    targetPort: 9296
  type: ClusterIP