apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: raskolnikov999/ingesoftv-taller2-ecommerce-cloudconfig
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka"
        - name: CONFIG_SERVER_URI
          value: "http://cloud-config:8888"