apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: ecommerce-dev
spec:
  type: ClusterIP
  selector:
    app: cloud-config
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888