trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: Bash@3
    displayName: 'Run semantic-release'
    inputs:
      targetType: 'inline'
      script: |
        docker run --rm \
          -v $(System.DefaultWorkingDirectory):/repo \
          -w /repo \
          -e GIT_AUTHOR_NAME="azure-devops-bot" \
          -e GIT_AUTHOR_EMAIL="yulukeitor@gmail.com" \
          -e GIT_COMMITTER_NAME="azure-devops-bot" \
          -e GIT_COMMITTER_EMAIL="yulukeitor@gmail.com" \
          -e GITHUB_TOKEN=$(GH_TOKEN) \
          ghcr.io/semantic-release/semantic-release:latest
