 version: '3'
 services: 
  zipkin: 
    image: openzipkin/zipkin 
    ports: 
      - 9411:9411 
    networks: 
      - microservices_network 

  service-discovery-container: 
    image: raskolnikov999/service-discovery:latest
    build:
      context: ./service-discovery
    ports: 
      - 8761:8761 
    networks:
      - microservices_network 
    environment: 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 

  cloud-config-container: 
    image: raskolnikov999/cloud-config:latest
    build:
      context: ./cloud-config
    ports: 
      - 9296:9296 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
  api-gateway-container: 
    image: raskolnikov999/api-gateway:latest 
    build:
      context: ./api-gateway
    ports: 
      - 8080:8080 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
  proxy-client-container: 
    image: raskolnikov999/proxy-client:latest 
    build:
      context: ./proxy-client
    ports: 
      - 8900:8900 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 
  order-service-container: 
    image: raskolnikov999/order-service:latest 
    build:
      context: ./order-service
    ports: 
      - 8300:8300 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 
  payment-service-container: 
    image: raskolnikov999/payment-service:latest 
    build:
      context: ./payment-service
    ports: 
      - 8400:8400 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 
  product-service-container: 
    image: raskolnikov999/product-service:latest 
    build:
      context: ./product-service
    ports: 
      - 8500:8500 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 
  shipping-service-container: 
    image: raskolnikov999/shipping-service:latest 
    build:
      context: ./shipping-service
    networks: 
      - microservices_network 
    ports: 
      - 8600:8600 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
  user-service-container: 
    image: raskolnikov999/user-service:latest 
    build:
      context: ./user-service
    ports: 
      - 8700:8700 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 
  favourite-service-container: 
    image: raskolnikov999/favourite-service:latest 
    build:
      context: ./favourite-service
    ports: 
      - 8800:8800 
    networks: 
      - microservices_network 
    environment: 
      - SPRING_PROFILES_ACTIVE=dev 
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/ 
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/ 

 networks: 
  microservices_network: 
    driver: bridge