controller:
  serviceType: NodePort

  startupProbe:
    httpGet:
      path: /login
      port: http
    failureThreshold: 60
    periodSeconds: 10
    initialDelaySeconds: 30

  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
