apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: jpnino/shipping-service:latest
        ports:
        - containerPort: 8600
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://zipkin:9411
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://cloud-config:9296/
        - name: EUREKA_CLIENT_REGION
          value: default
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: myzone
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: http://service-discovery:8761/eureka
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://service-discovery:8761/eureka/
        - name: EUREKA_INSTANCE
          value: "shipping-service"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
  - port: 8600
    targetPort: 8600
  type: ClusterIP