apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: ecommerce-dev
spec:
  type: ClusterIP
  selector:
    app: shipping-service
  ports:
    - protocol: TCP
      port: 8600
      targetPort: 8600