apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: raskolnikov999/product-service:latest
        ports:
        - containerPort: 8500
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: stage
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://zipkin:9411
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://cloud-config:9296/
        - name: EUREKA_CLIENT_REGION
          value: default
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: myzone
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: http://service-discovery:8761/eureka
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://service-discovery:8761/eureka/
        - name: EUREKA_INSTANCE
          value: "product-service"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: product-service 
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: 8500
    targetPort: 8500
  type: ClusterIP