apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ecommerce-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: raskolnikov999/ingesoftv-taller2-ecommerce-apigateway
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery.ecommerce-dev.svc.cluster.local:8761/eureka" # Use the service name and namespace for internal communication
        - name: SPRING_CONFIG_IMPORT
          value: "http://cloud-config.ecommerce-dev.svc.cluster.local:8888"
        - name: CONFIG_SERVER_URI
          value: "http://cloud-config.ecommerce-dev.svc.cluster.local:8888"
        - name: SPRING_APPLICATION_NAME
          value: "api-gateway"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "true"