apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce-dev
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500