apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: raskolnikov999/ingesoftv-taller2-ecommerce-userservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8700
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery.ecommerce-dev.svc.cluster.local:8761/eureka" # Use the service name and namespace for internal communication
        - name: SPRING_CONFIG_IMPORT
          value: "http://cloud-config.ecommerce-dev.svc.cluster.local:8888"
        - name: CONFIG_SERVER_URI
          value: "http://cloud-config.ecommerce-dev.svc.cluster.local:8888"  # FQDN completo
        - name: SPRING_APPLICATION_NAME
          value: "user-service"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "true"